Repository JuliaSparse/SparseArrays.jl, pull requests merged in 2022-12, with the labels that each got.

#284 Improved memory usage when creating the sparsity pattern
  src/sparsematrix.jl
  test/sparsematrix_constructors_indexing.jl
Labels: enhancement

#310 doc: add compat annotation for spzeros method for pattern creation.
  src/sparsematrix.jl
Labels: documentation

#314 Resize buffers in `sparse!` to satisfy buffer checks in constructor
  src/sparsematrix.jl
  test/sparsematrix_constructors_indexing.jl
Labels: backport 1.8, backport 1.9
