Repository JuliaSparse/SparseArrays.jl, pull requests merged in 2022-11, with the labels that each got.

#283 Fix order of triangular and adjortrans wrappers
  src/linalg.jl
Labels: linear algebra, backport 1.8

#272 Remove temporary circshift direction workaround
  src/SparseArrays.jl
  src/sparsematrix.jl
  src/sparsevector.jl
Labels: backport 1.8

#287 Bugfix in getindex for Matrices with one dimension 0
  src/sparsevector.jl
  test/sparsematrix_constructors_indexing.jl
  test/sparsevector.jl
Labels: backport 1.8

#291 Clean up mul/div code of sparse and diagonal
  src/linalg.jl
Labels: performance, linear algebra, backport 1.8, backport 1.9
